export const DEFAULT_ELEVEN_LABS_VOICES = [
  { label: 'Alice', value: 'Xb7hH8MSUJpSbSDYk0k2' },
  { label: 'Aria', value: '9BWtsMINqrJLrRacOk9x' },
  { label: 'Bill', value: 'pqHfZKP75CvOlQylNhV4' },
  { label: 'Brian', value: 'nPczCjzI2devNBz1zQrb' },
  { label: 'Callum', value: 'N2lVS1w4EtoT3dr4eOWO' },
  { label: 'Charlie', value: 'IKne3meq5aSn9XLyUdCD' },
  { label: 'Charlotte', value: 'XB0fDUnXU5powFXDhCwa' },
  { label: 'Chris', value: 'iP95p4xoKVk53GoZ742B' },
  { label: 'Daniel', value: 'onwK4e9ZLuTAKqWW03F9' },
  { label: 'Eric', value: 'cjVigY5qzO86Huf0OWal' },
  { label: 'George', value: 'JBFqnCBsd6RMkjVDRZzb' },
  { label: 'Jessica', value: 'cgSgspJ2msm6clMCkdW9' },
  { label: 'Laura', value: 'FGY2WhTYpPnrIDTdsKH5' },
  { label: 'Liam', value: 'TX3LPaxmHKxFdv7VOQHJ' },
  { label: 'Lily', value: 'pFZP5JQG7iQjIQuC4Bku' },
  { label: 'Matilda', value: 'XrExE9yKIg1WjnnlVkGX' },
  { label: 'River', value: 'SAz9YHcvj6GT2YYXdXww' },
  { label: 'Roger', value: 'CwhRBWXzGAHq8TQ4Fs17' },
  { label: 'Sarah', value: 'EXAVITQu4vr4xnSDxMaL' },
  { label: 'Will', value: 'bIHbv24MWmeRgasZH58o' },
]
